### ISSUE TITLE
考虑使用最高分提交代替最后一次提交

### ISSUE THREAD

**Issue by liuxukun2000** [JCoder-Pro/FeedBack#10]
考虑使用最高分提交代替最后一次提交，如有需要或建议请在此处留言。
目前此功能优先级较低，如果有需要的人数较多会考虑优先更新。

**Comment by RoderickQiu** [comment]
我觉得很有必要……
> 另，每次提交都会覆盖上一次，我也真是谢谢了。因为每次进submit的页面都会自动跳回到题目A，太容易给题目A再评一次了，然后就0分G了，还得再来一次。
