### ISSUE TITLE
提交记录返回题面的按钮失效

### ISSUE THREAD

**Issue by hfhongzy** [JCoder-Pro/FeedBack#19]
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/36727914/203962832-55f55903-2716-44c7-a668-5065edfad422.png">

什么时候能修修啊，每次都 Target Failed，然后从主页开始往里点

**Comment by seoi2017** [comment]
您好，该问题现已初步修复，如后续产生其他问题或有更多建议，欢迎及时反馈
